from LinkList import*
mylist = MyList()
mylist.addFirst("A",20)
mylist.addFirst("B",21)
mylist.addFirst("C",22)
mylist.addLast("X",19)
mylist.addLast("Y",18)
mylist.addLast("Z",17)
mylist.addIndex1("Aa",25,3)
mylist.display()
index = mylist.findIndex(3)
mylist.addIndex1("qq",25,index)
mylist.sortEven()
mylist.display()